---
# from https://github.com/soehlert/osx-ansible/blob/master/roles/osx_base/tasks/main.yml
- name: Check hostname
  command: hostname
  register: current_hostname
  changed_when: false
  tags: osx

- name: Set computer name
  command: "scutil --set {{ item }} Zeitgeist"
  loop:
    - ComputerName
    - LocalHostName
  become: true
  become_user: root
  when: current_hostname.stdout != "Zeitgeist"
  tags: osx

- name: Defaults host name
  osx_defaults:
    domain: com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "Zeitgeist"
  become: true
  become_user: root
  tags: osx
