---
- name: Check OSX softwareupdate
  command: "softwareupdate --all --install --force"
  register: softwareupdate
  changed_when: "softwareupdate.rc != 0 and 'No updates are available.' not in softwareupdate.stderr"
  tags: softwareupdate
