---
- name: "Configure Homebrew taps"
  homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"

- name: "Install Homebrew formulae"
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
    upgrade_all: true
  loop: "{{ brew_packages }}"

- name: "Install Homebrew casks"
  homebrew_cask:
    name: "{{ item }}"
    greedy: true
    state: present
  ignore_errors: true
  loop: "{{ cask_packages }}"

- name: "Install QuickLook plugins"
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  ignore_errors: true
  loop: "{{ cask_ql_packages }}"

- name: Cleanup brew
  command: brew cleanup
