---
- name: "Configure Homebrew taps"
  homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"

- name: "Install Homebrew formulae"
  homebrew:
    name: "{{ item }}"
    state: latest
    update_homebrew: yes
    upgrade_all: yes
  loop: "{{ brew_packages }}"

- name: "Install Homebrew casks"
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  loop: "{{ cask_packages }}"

- name: "Install QuickLook plugins"
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  loop: "{{ cask_ql_packages }}"
  tags: runthis

- name: Cleanup brew
  command: brew cleanup
  tags: runthis