---
# Figured this out myself via 'defaults read com.noodlesoft.Hazel'
- name: Set Hazel rules sync folder
  osx_defaults: domain=com.noodlesoft.Hazel key={{ item.key }} type={{ item.type }} value={{ item.value }}
  with_items:
    # Set folder where we save our rules files
    - {key: "NSNavLastRootDirectory", type: "string", value: "~/Code/Private/dotfiles/ansible/roles/hazel/files"}
    # Ensure secure deletion of items in trash
    - {key: "TrashSecureDelete", type: "int", value: "1"}
  notify:
    - Kill Hazel
  tags: hazel
