
# Homebrew
#export PATH=${HOME}/Homebrew/bin:${PATH}
#export PATH=${HOME}/Homebrew/sbin:${PATH}
#export PATH=${HOME}/Homebrew/bib:${PATH}

# show path in window title of iTerm
PROMPT_TITLE='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}\007"'
export PROMPT_COMMAND="${PROMPT_TITLE}; ${PROMPT_COMMAND}"

# for OF<->Trello sync gem
export OF_FOLDER="My Trello Boards"

# path for Homebrew coreutils$(brew --prefix coreutils)/libexec/gnubin
export PATH=$(brew --prefix coreutils)/libexec/gnubin:${PATH}

# Add `~/bin` to the `$PATH`
export PATH=${HOME}/bin:/usr/local/sbin:${PATH}

# Add ruby to the path
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/Users/jan/.rbenv/shims:$PATH"

# node
export PATH="/usr/local/opt/node@14/bin/node:$PATH"

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{bash_prompt,exports,aliases}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Add tab completion for many Bash commands
#if which brew &> /dev/null && [ -f "$(brew 
#--prefix)/share/bash-completion/bash_completion" ]; then
#	source "$(brew --prefix)/share/bash-completion/bash_completion";
#elif [ -f /etc/bash_completion ]; then
#	source /etc/bash_completion;
#fi;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# load iTerm2 Shell Integration
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# init rbenv
val "$(rbenv init -)"

#python
export PATH=/usr/local/share/python:$PATH
export PATH=/Users/jan/Library/Python/3.9/lib/python/site-packages:$PATH
