#!/usr/bin/env bash

# Can't figure out how to fix this, therefore let's disable shellcheck for this line
# shellcheck disable=SC1090
[ -n "$PS1" ] && source ~/.bash_profile;

# pyenv
eval "$(pyenv init -)"
