#!/usr/bin/env bash

# show current dir in iTerm tab title
# source: https://gist.github.com/phette23/5270658
if [ "$ITERM_SESSION_ID" ]; then
  export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"; ':"$PROMPT_COMMAND";
fi

# prompt
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1

# ls
export LSCOLORS=ExFxBxDxCxegedabagacad

# brew related
export HOMEBREW_CASK_OPTS="--appdir=/Applications --fontdir=/Library/Fonts --qlplugindir=/Library/QuickLook"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
# shellcheck disable=SC2155
export PATH=$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH
# path for Homebrew coreutils$(brew --prefix coreutils)/libexec/gnubin
# shellcheck disable=SC2155
export PATH=$(brew --prefix coreutils)/libexec/gnubin:${PATH}

# Make nano the default editor.
export EDITOR='nano';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';
export LC_CTYPE=en_US.UTF-8;

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# ruby
export PATH=/Users/jan/.rbenv/shims:$PATH

#pyenv for python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Fix Ansible
export ANSIBLE_PYTHON_INTERPRETER="$(which python)"

# Add `~/bin` to the `$PATH`
export PATH=${HOME}/bin:${PATH}

# node
# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';
export PATH="$PATH:./node_modules/.bin"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm


# remove duplicate PATH entries
PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')

# dump your path like this
# echo $PATH | tr ':' '\n'. | sort

# Remove annoying warning that I should switch to zsh
# https://support.apple.com/en-us/HT208050
export BASH_SILENCE_DEPRECATION_WARNING=1
