---
- name: Install Node Packages
  npm: name={{ item }} state=present global=yes
  with_items:
    - eslint
    - joi
    - jshint
    - netlify-cli
    - npm-upgrade
    - npm
    - prettier
    - yarn
  tags: npm
