---
- name: Get all currently installed pip modules
  ansible.builtin.shell: "set -o pipefail && pip list | tail -n +3 | awk '{ print $1 }'"
  register: installedpipmodules
  changed_when: false
  tags: pip

- name: Upgrade pip itself
  ansible.builtin.pip:
    name: pip
    extra_args: --upgrade
  tags: pip

- name: Install pip modules (skip if already installed)
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop: "{{ default_pip_modules }}"
  when: item not in installedpipmodules.stdout
  tags: pip

- name: Get all currently installed and outdated pip modules
  ansible.builtin.shell: "set -o pipefail && pip list --outdated | tail -n +3 | awk '{ print $1 }'"
  register: outdatedpipmodules
  changed_when: false
  tags: pip

- name: Update all currently installed and outdated pip modules
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: --upgrade
  with_items: "{{ outdatedpipmodules.stdout_lines }}"
  register: pkg_result
  until: pkg_result is success
  tags: pip
