---
brew_taps:
  - heroku/brew
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services

brew_packages:
  - python
  - ansible
  - autoconf
  - automake
  - awscli
  - bash
  - bash-completion@2
  - binutils
  - coreutils
  - diffutils
  - duf
  - duti
  - exiftool
  - gh
  - git
  - libffi
  - unbound
  - nghttp2
  - gnupg
  - gzip
  - htop
  - jq
  - less
  - mas
  - nano
  - nmap
  - node
  - openssh
  - postgresql
  - ruby-build
  - rbenv
  - rsync
  - ruby
  - ssh-copy-id
  - tidy-html5
  - tree
  - wget
  - wifi-password
  - zlib
  - zsh
  - heroku/brew/heroku

cask_packages:
  - 1password
  - arq
  - cyberduck
  - dropbox
  - dupeguru
  - firefox
  - google-chrome
  - hazel
  - iterm2
  - kindle
  - launchcontrol
  - maccy
  - ngrok
  - omnifocus
  - omniplan
  - osxfuse
  - scrivener
  - sequential
  - simple-comic
  - skype
  - slack
  - sourcetree
  - spotify
  - superduper
  - tabula
  - teamviewer
  - the-unarchiver
  - thunderbird
  - timing
  - transmission
  - veracrypt
  - virtualbox
  - vlc
  - zoom

cask_ql_packages:
  - provisionql
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - qlvideo
  - quicklook-csv
  - quicklook-json
  - suspicious-package
  - webpquicklook
