---
# Based on https://github.com/fgimian/macbuild-ansible/blob/master/roles/default_apps/tasks/main.yaml
- name: Ensure duti is installed
  community.general.homebrew:
    name: duti
    state: present
  tags: duti

# check if current association is same bundle_id as expected
# if yes, write into stdout
# if no, keep stdout empty
# read this into duti_output for later use
- name: Check file type association
  ansible.builtin.command: "duti -x {{ item.1 }} | grep {{ item.0.bundle_id }}"
  with_subelements:
    - "{{ duti_default_apps_associations }}"
    - utis
  register: duti_output
  changed_when: duti_output.rc == 1
  failed_when: "'Failed to get default application' in duti_output.stderr"
  tags: duti

# - debug:
#    var: duti_output
#  tags: duti

# if we have something in item.stdout, do nothing
# if item.stdout is empty, set assocation
- name: Update file type association
  ansible.builtin.command: "duti -s {{ item.item.0.bundle_id }} {{ item.item.1 }} all"
  with_items: "{{ duti_output.results | list }}"
  # only do this when our check in the previous task resulted in an
  # error, meaning that the association is not what we expected
  when: item.rc == 1
  notify:
    - Kill Finder
  tags: duti
