---
# This is not a work of art, but out of necessity. I know this can be made much nicer

# update & upgrade
- name: Update & upgrade brew formulae
  community.general.homebrew:
    update_community.general.homebrew: true
    upgrade_all: true
  tags: maintenance, softwareupdate

- name: Update & upgrade brew casks
  community.general.homebrew_cask:
    upgrade_all: true
  tags: maintenance, softwareupdate

# cleanup
- name: Cleanup brew
  ansible.builtin.command: brew cleanup --prune=all -s
  tags: maintenance, softwareupdate

# delete brew caches
# figure out cache path
- name: Find brew cache path / $(brew --cache)
  ansible.builtin.command: brew --cache
  register: brewcachepath
  tags: maintenance, softwareupdate

# Run "rm -rfv {{ brewcachepath.stdout }}"
- name: Delete brew cache
  ansible.builtin.file:
    path: '{{ brewcachepath.stdout }}'
    state: absent
  tags: maintenance, softwareupdate

- name: Repair taps
  ansible.builtin.command: brew tap --repair
  tags: maintenance, softwareupdate
