---
# This is not a work of art, but out of necessity. I know this can be made much nicer

# update & upgrade
- name: Update & upgrade brew
  homebrew:
    update_homebrew: true
    upgrade_all: true
  tags: maintenance

# cleanup
- name: Cleanup brew
  command: brew cleanup
  tags: maintenance

- name: Upgrade all Mac App Store apps
  mas:
    upgrade_all: true
  tags: maintenance

- name: Check OSX softwareupdate
  command: "softwareupdate --all --install --force"
  register: softwareupdate
  changed_when: "softwareupdate.rc != 0 and 'No updates are available.' not in softwareupdate.stderr"
  tags: maintenance

# repair permissions
# figure out current user id
- name: Find user id / $(id -u)
  command: id -u
  register: userid
  tags: maintenance

# warning: this command can not be canceled. Runtime is ca. 2 mins for 500gb
- name: Run 'diskutil resetuserpermissions / $(id -u)'
  command: "diskutil resetuserpermissions / {{ userid.stdout }}"
  become: true
  tags: maintenance, skip_ansible_lint

# Check disk
# Get list with 'diskutil list'
- name: Run 'diskutil verifyVolume /dev/disk1'
  command: "diskutil verifyVolume /dev/disk1"
  become: true
  tags: maintenance, skip_ansible_lint

# flush DNS
- name: Run 'dscacheutil -flushcache && killall -HUP mDNSResponder'
  command: "dscacheutil -flushcache && killall -HUP mDNSResponder"
  become: true
  tags: maintenance, skip_ansible_lint

# empty all Trashes
- name: Run 'rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash;'
  command: "rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash;"
  become: true
  tags: maintenance, skip_ansible_lint

# empty all Trashes
- name: Run 'rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash;'
  command: "rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash;"
  become: true
  tags: maintenance, skip_ansible_lint

# Speed up terminal by clearing ASL logs
- name: Run 'rm -rfv /private/var/log/asl/*.asl'
  command: "rm -rfv /private/var/log/asl/*.asl"
  become: true
  tags: maintenance, skip_ansible_lint

# Delete launch service quarantine (list of all files ever downloaded)
- name: Clean up LaunchServices quarantine
  command: "bash {{ ansible_user_dir }}/Code/private/dotfiles/bin/clean_osx_downloads.sh"
  tags: maintenance

# Reset LaunchServices db
# Splitting this into 2 lines to stay under our line limit of 180 chars
- name: Clean up LaunchServices to remove duplicates in the “Open With” menu
  command: >
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister
    -kill -r -domain local -domain system -domain user && killall Finder
  become: true
  tags: maintenance
