---
- name: Ensure sublime-text brew cask is installed
  homebrew_cask:
    name: sublime-text
    greedy: true
    state: present
  register: result
  tags: sublimetext

- name: Remove symlink
  file:
    path: "/Users/jan/Library/Application Support/Sublime Text/Packages/User"
    state: absent
  tags: sublimetext

# Symlink
- name: Symlink Sublime Text User Packages+Prefs
  file:
    src: "/Users/jan/Code/Private/dotfiles/ansible/roles/sublimetext/files/User/"
    dest: "/Users/jan/Library/Application Support/Sublime Text/Packages/User"
    state: link
    force: true
    follow: false
  tags: sublimetext

# Important to understand:
# Don't symlink into /usr/bin, this is blocked by OSX.
# Use /usr/local/bin instead
- name: "Ensure symlinks in bin"
  file:
    src: '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'
    dest: "/usr/local/bin/{{ item }}"
    state: link
  become: true
  with_items:
    - subl
    - sublime
  tags: sublimetext
